```{r message=FALSE, warning=FALSE}
#setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
library(tidyverse)
library(rusboost)
library(rpart)
suppressPackageStartupMessages(library(ISLR))
suppressPackageStartupMessages(library(pROC))
```

```{r, message=FALSE}
#load("C:/Users/cjy2001/OneDrive - Middlebury College/Middlebury Academic/Fall 2021/Project/11.4.RData")
data <- read_csv("uscecchini28.csv")
data$misstate <- factor(data$misstate)
```

```{r Creating data}
split_train_test <- function (year, data) {
  train <<- data %>%
    filter(fyear <= year - 2)
  test <<- data %>%
    filter(fyear == year)
}

split_train_test(2003, data)
train_3 <- train
test_3 <- test
```

```{r}
set.seed(5)
year3_time_5000 <- system.time(year3_model_5000 <- rusb(formula = misstate ~ act + ap + at + ceq + che + cogs + csho + dlc + dltis + dltt + dp
              + ib + invt + ivao + ivst + lct + lt + ni + ppegt + pstk + + re + rect + sale + sstk + txp + txt + xint + 
                prcc_f,
              data = train_3,
              boot = FALSE,
              iters = 5000, 
              control = rpart.control(minsplit = 5),
              sampleFraction = 0.5,
              idx = train_3$misstate == 0)
)
```

```{r}
year3_preds_5000 <- predict.rusb(year3_model_5000, data.frame(test_3))
```


