```{r message=FALSE, warning=FALSE}
#setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
library(tidyverse)
library(rusboost)
library(rpart)
suppressPackageStartupMessages(library(ISLR))
suppressPackageStartupMessages(library(pROC))
#library(rattle)
#library(ebmc)
#Package ebmc was removed from the CRAN repository.
#Archived on 2021-03-16 as requires archived package 'DMwR'
```

```{r, message=FALSE}
#load("C:/Users/cjy2001/OneDrive - Middlebury College/Middlebury Academic/Fall 2021/Project/11.4.RData")
data <- read_csv("uscecchini28.csv")
data$misstate <- factor(data$misstate)
```

```{r Creating data}
split_train_test <- function (year, data) {
  train <<- data %>%
    filter(fyear <= year - 2)
  test <<- data %>%
    filter(fyear == year)
}
```

```{r}
split_train_test(2006, data)
train_6 <- train
test_6 <- test
split_train_test(2007, data)
train_7 <- train
test_7 <- test
split_train_test(2008, data)
train_8 <- train
test_8 <- test
```

```{r}
set.seed(5)

year7_time_3000 <- system.time(year7_model_3000 <- rusb(formula = misstate ~ act + ap + at + ceq + che + cogs + csho + dlc + dltis + dltt + dp
              + ib + invt + ivao + ivst + lct + lt + ni + ppegt + pstk + + re + rect + sale + sstk + txp + txt + xint + 
                prcc_f,
              data = train_7,
              boot = FALSE,
              iters = 3000, 
              control = rpart.control(minsplit = 5),
              sampleFraction = 0.5,
              idx = train_7$misstate == 0)
)

year8_time_3000 <- system.time(year8_model_3000 <- rusb(formula = misstate ~ act + ap + at + ceq + che + cogs + csho + dlc + dltis + dltt + dp
              + ib + invt + ivao + ivst + lct + lt + ni + ppegt + pstk + + re + rect + sale + sstk + txp + txt + xint + 
                prcc_f,
              data = train_8,
              boot = FALSE,
              iters = 3000, 
              control = rpart.control(minsplit = 5),
              sampleFraction = 0.5,
              idx = train_8$misstate == 0)
)
```

```{r}
year6_preds_3000_2 <- predict.rusb(year6_model_3000_2, data.frame(test_6))
year7_preds_3000 <- predict.rusb(year7_model_3000, data.frame(test_7))
year8_preds_3000 <- predict.rusb(year8_model_3000, data.frame(test_8))
```

```{r}
# year6_time_3000_2 <- system.time(year6_model_3000_2 <- rusb(formula = misstate ~ act + ap + at + ceq + che + cogs + csho + dlc + dltis + dltt + dp
#               + ib + invt + ivao + ivst + lct + lt + ni + ppegt + pstk + + re + rect + sale + sstk + txp + txt + xint + 
#                 prcc_f,
#               data = train_6,
#               boot = FALSE,
#               iters = 3000, 
#               control = rpart.control(minsplit = 5),
#               sampleFraction = 0.5,
#               idx = train_6$misstate == 0)
# )
```


